# Generated by Django 2.2.6 on 2019-10-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcreater', '0001_nikhilkoneru'),
    ]

    operations = [
        migrations.CreateModel(
            name='FLinsurancesamplecsvzip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policyid', models.CharField(max_length=100)),
                ('statecode', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('eq_site_limit', models.CharField(max_length=100)),
                ('hu_site_limit', models.CharField(max_length=100)),
                ('fl_site_limit', models.CharField(max_length=100)),
                ('fr_site_limit', models.CharField(max_length=100)),
                ('tiv_2011', models.CharField(max_length=100)),
                ('tiv_2012', models.CharField(max_length=100)),
                ('eq_site_deductible', models.CharField(max_length=100)),
                ('hu_site_deductible', models.CharField(max_length=100)),
                ('fl_site_deductible', models.CharField(max_length=100)),
                ('fr_site_deductible', models.CharField(max_length=100)),
                ('point_latitude', models.CharField(max_length=100)),
                ('point_longitude', models.CharField(max_length=100)),
                ('line', models.CharField(max_length=100)),
                ('construction', models.CharField(max_length=100)),
                ('point_granularity', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='SalesJancsv',
        ),
    ]
