# Generated by Django 2.2.6 on 2019-10-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcreater', '0001_nikhilkoneru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesjancsv',
            name='latitude',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='salesjancsv',
            name='longitude',
            field=models.FloatField(default=None),
        ),
    ]
