# Generated by Django 2.2.6 on 2019-10-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcreater', '0002_nikhilkoneru'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesJancsv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('payment_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('account_created', models.CharField(max_length=100)),
                ('last_login', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='FLinsurancesamplecsvzip',
        ),
    ]
