# Generated by Django 2.2.6 on 2019-11-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesJan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('product', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('price', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('payment_type', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('account_created', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('last_login', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'SalesJan',
            },
        ),
    ]
