# Generated by Django 2.2.6 on 2019-11-23 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_support', '0001_nikhilkoneru'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesJan',
        ),
    ]
