# Generated by Django 2.2.6 on 2019-11-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_support', '0003_nikhilkoneru'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechCrunchcontinentalUSA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permalink', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('company', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('numemps', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('category', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('fundeddate', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('raisedamt', models.IntegerField(blank=True, default=None, null=True)),
                ('raisedcurrency', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('round', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'TechCrunchcontinentalUSA',
            },
        ),
    ]
