# Generated by Django 2.2.6 on 2019-11-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_support', '0004_nikhilkoneru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sacramentorealestatetransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('zip', models.IntegerField(blank=True, default=None, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('beds', models.IntegerField(blank=True, default=None, null=True)),
                ('baths', models.IntegerField(blank=True, default=None, null=True)),
                ('sq__ft', models.IntegerField(blank=True, default=None, null=True)),
                ('type', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('sale_date', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'Sacramentorealestatetransactions',
            },
        ),
    ]
